name: Check pipeline

on: [push]

jobs:
  build:
    name: linting and type checking
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install untuntu packages
      run: |
        sudo apt-get update
        sudo apt-get update
        sudo apt-get -y install build-essential git make autoconf automake libtool \
        pkg-config cmake ninja-build libasound2-dev libpulse-dev libaudio-dev \
        libjack-dev libsndio-dev libsamplerate0-dev libx11-dev libxext-dev \
        libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libwayland-dev \
        libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
        libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev fcitx-libs-dev
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        python -m venv .venv
        source .venv/bin/activate
        poetry install
    - name: Print contents of repo
      run: |
        ls -la
    - name: Analysing the code with pylint
      if: success() 
      run: |
        source .venv/bin/activate
        poetry run pylint src
    - name: Run Mypy
      run: |
        source .venv/bin/activate
        poetry run mypy src
    - name: Run tests
      run: |
        source .venv/bin/activate
        poetry run pytest tests --cov --cov-report=xml --verbose -p no:warnings
