name: Python linting and type checking with Pylint and Mypy

on: [push]

jobs:
  build:
    name: linting and type checking
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11
      uses: actions/setup-python@v1
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        python -m venv .venv
        source .venv/bin/activate
        poetry install
    - name: Analysing the code with pylint
      if: success() 
      run: |
        source .venv/bin/activate
        poetry run pylint src
    - name: Run Mypy
      run: |
        source .venv/bin/activate
        poetry run mypy src
